### ISSUE TITLE
sleep syncing return "Failure: 4" caused by mixing deprecated code with not deprecated code

### ISSUE THREAD

**Issue by davidguerrerolopez** [StasDoskalenko/react-native-google-fit#186] opened 2020-09-01 16:51 UTC
**### Sync sleep data error**

after react-native-google-fit got support for sleep hours, we started facing intermittent issues that prevent customers to read and sync sleep records, the customer is only able to read and sync steps records. It also caused other issue related to disconnect functionality., after some research, testing, and debugging we realized that the issue was caused because at the library level we are mixing deprecated code(steps) with new code (sleep), apparently, the deprecated implementation do not request for all the required permissions to read sleep records.

looking at android developers tools, we found a specific error that mentions that we do not have enough permission to read sleep records
`Failure: 4: The user must be signed in to make this API call`

that error message was also returned on disconnect call after we did exhaustive research about those errors, the posts mention some issues related to the cert key was not added correctly to google cloud, but apparently our configuration was right.

the way to fix this was by creating a function into `SleepHistory.java` to fix that state when a customer is partially connected(able to read steps records, but not able to read sleep records), that function was placed in to `addOnFailureListener ` of `Fitness.getSessionsClient(this.mReactContext, gsa)`, and the function looks like this

```
`
private void fixDisconnectedState(int requestCode) {
    FitnessOptions fitnessOptions = FitnessOptions.builder()
        .addDataType(DataType.TYPE_ACTIVITY_SEGMENT, FitnessOptions.ACCESS_READ)
        .build();
        // Get currently signed in account (or null)
    GoogleSignInAccount account = GoogleSignIn.getLastSignedInAccount(SleepHistory.this.mReactContext);
    if (!GoogleSignIn.hasPermissions(account, fitnessOptions)) {
        // Note: this launches a sign-in flow, however the code to detect
        // the result of the sign-in flow and retry the API call is not
        // shown here.
        GoogleSignIn.requestPermissions(this.mReactContext.getCurrentActivity(), requestCode, account, fitnessOptions);
        return;
    }  
}
`
```

we know this probably could be improved.

**Comment by aboveyunhai** [comment] 2020-09-02 06:37
@davidguerrerolopez The issue was informed multiple times. and the sign in-out trick, but I never got confirm it can work from that person. 
https://github.com/StasDoskalenko/react-native-google-fit/issues/175#issuecomment-674197633
By the way, step (at least the fetch data part), is using the not deprecated API right before the sleep feat added. So the issue comes from somewhere else.

There are a lot of code duplications between functions and a little bit of disorganize among functions (Some functions like `sleep` requires callback as a must otherwise it's going to crush, some take it as a option). 
In fact, the callback arg can be simply dropped and handle by your own after `await getSleepData(options)` 
instead of `const callback = function(){}; getSleepData(options, callback)`, it doesn't bring any advantages besides personal preferences from past merge ASAIK.   
I really want to get rid of it to simplify the codebase as well as unite all functions into one common standard, but I am not sure how it would affect users like you.

**Comment by davidguerrerolopez** [comment] 2020-09-02 16:20
@aboveyunhai thanks for your answer, 
I'm not sure if this help but the solution that I mentioned before was the only solution that works properly for us, I have to mention that I work at the same company than the guy that introduced `sleepHistory.java` class, and that class was introduced in order to add the support to our app, regarding to the `sing in-out trick`, I have to said that it only works for `production.keystores`, but we don't want customer disconnecting and reconnecting manually if we can fix it directly at the catch of `Fitness.getSessionsClient`.

I agreed with you about the callback arg, is not a problem for us refactor a bit our implementation with this library, I think the async/await is also a lot better, so I think it should not be a big issue for users like me, our biggest concern right now is to get this working properly with the right permission to read sleep data and get `disconnect/disabledFit` working properly

**Comment by aboveyunhai** [comment] 2020-09-02 17:41
@davidguerrerolopez  since your solution includes permission check, I believe the problem comes from the missing permission and I also checked the official doc.  Not sure if this is the problem but I wish you can try this out in .js instead of native side, it should just do the same trick, if the problem is still reproducible
```
// Note: The android.permission.ACTIVITY_RECOGNITION permission is
// required to read DataType.TYPE_ACTIVITY_SEGMENT
```

```
import { PermissionsAndroid } from "react-native";
const yourFunction = async () => {
  try {
    const granted = await PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.ACTIVITY_RECOGNITION,
      {
        title: "title",
        message: "message"
        buttonNeutral: "Ask Me Later",
        buttonNegative: "Cancel",
        buttonPositive: "OK"
      }
    );
    if (granted === PermissionsAndroid.RESULTS.GRANTED) {
       // do your sleep functions here
    } else {
      //  do something else / user don't wanna give the permission
    }
  } catch (err) {
    console.warn(err);
  }
};
```

I know it's a little verbose, request in native side will run silently but complete dismiss the user right.

**Comment by davidguerrerolopez** [comment] 2020-09-02 17:48
@aboveyunhai yeah you are right, it came from the permissions, is great to know we can do it in our front end side, instead of the native side, if this works well will fix our problem let me try your suggestion, for sure I will back with news about it, probably this could be helpful for somebody else as well.

**Comment by aboveyunhai** [comment] 2020-09-02 18:01
@davidguerrerolopez  you might want to check permission first so it's not necessary to trig the panel every time

**Comment by davidguerrerolopez** [comment] 2020-09-15 18:12
@aboveyunhai looks like your approach did not fix the issue, after some research I figured out that `ACTIVITY_RECOGNITION ` is not part of `PermissionsAndroid.PERMISSIONS`, another observation about this is that the error show the number "4" as error code, so for that reason, I requested permissions for that specific error code. do you know if there is another way to request permission from the JS side?

**Comment by aboveyunhai** [comment] 2020-09-15 18:26
@davidguerrerolopez You are right. It seems like RN does not support this particular permission but I misread it somewhere from google doc. I did see some ppl tried to add this feature to RN but it did not get merged successfully.

 Then the only way we can go is stick in the native side like you did.  There is not naive JS way for this permission, but you can request other general permissions listed in the RN doc.

**Comment by davidguerrerolopez** [comment] 2020-09-15 18:34
@aboveyunhai I was able to request permission for `ACTIVITY_RECOGNITION` it prompt a request window for activity recognition, by using your approach but it did not fix the issue, looks like its no a issue with `ACTIVITY_RECOGNITION`, its already added to our `AndroidManifes.xml`, is there a way to include my fix into `SleepHistory.java`? if possible I can create a PR so it could be helpful for the people with the same issue

**Comment by aboveyunhai** [comment] 2020-09-15 19:23
@davidguerrerolopez Go ahead and do it, Im just a contributor by the way. My only suggestion is to change the function name to `requestSleepPermission` or `requestPermision` instead of `fixSomething`

**Comment by davidguerrerolopez** [comment] 2020-09-15 19:24
@aboveyunhai I will do it, thanks

**Comment by StasDoskalenko** [comment] 2020-09-15 19:26
@aboveyunhai hey! I have invited you as a collaborator 👍 Thank you very much for helping to maintain this repo!

**Comment by aboveyunhai** [comment] 2020-09-15 19:55
@StasDoskalenko  Im glad to hear that. Hope we can make it better

**Comment by davidguerrerolopez** [comment] 2020-09-15 21:12
guys @aboveyunhai @StasDoskalenko Im trying to apply the fix, but I have some doubts regarding the catch method where the call for `requestSleepPermission ` will exist, looks like that catch is being executed in two scenarios, when there is not sleep data and when this state occurs `Failure: 4: The user must be signed in to make this API call`, so as you can see there are two different strings from the exception class, My question is whats the best option to validate this in order to execute `requestSleepPermission` only for `Failure: 4` scenario?

**Comment by aboveyunhai** [comment] 2020-09-15 22:16
im not exactly sure about the exact code
but my logic will be something like   
```
if (does not have permission){ 
  run some functions/codes to get necessary permission 
}

if(has permission) {
 run sleepfuncton to get data
} else {
 return something wrong
}
```
Though the problem might be if permission request permission failed/or something else happen, sleep function will never be run

**Comment by davidguerrerolopez** [comment] 2020-09-16 17:52
@aboveyunhai  there is a problem within `GoogleSignIn.hasPermissions`for some reason it always return true, but I still getting the `Failure: 4: The user must be signed in to make this API call` for sleep records, the only way to successfully catch this error is at the catch of the sleep records call, is ok to add the `GoogleSignin.requestPermissions` as handle exception? maybe by defining a constant for `Failure: 4: The user must be signed in to make this API call` and comparing it between `e.getMessage()`

**Comment by aboveyunhai** [comment] 2020-09-16 21:27
Maybe you can just do it if it really solve the issue. Then I can test out the PR if I had some free time recently.
My own problem with this issue is that I was not able to reproduce the problem since my account is signed in with necessary permission I guess.

**Comment by davidguerrerolopez** [comment] 2020-09-16 21:34
@aboveyunhai there is a way to cause that error, I was able te replicated it by removing the permissions from Google fit app, if you goto GoogleFit app -> Profile -> Settings -> Manage connected apps and remove the permissions to your app, it could replicate the issue.

**Comment by aboveyunhai** [comment] 2020-09-28 00:30
Merge #187 addresses this issue.

**Closed by aboveyunhai** 2020-09-28 00:30 UTC
