### ISSUE TITLE
Does it work for ios?

### ISSUE THREAD

**Issue by lucapaciello-tech4care** [StasDoskalenko/react-native-google-fit#271] opened 2022-01-20 11:24 UTC
I used it successfully on android. But i got null object trying to use it in ios. Is this library done for working in ios, so mine is just a configuration issue, or does it only work in android?__

**Comment by aboveyunhai** [comment] 2022-01-25 18:27
duplicate of #242

**Closed by aboveyunhai** 2022-01-25 18:27 UTC
